CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=0ed8f0a9-cfc1-4a2c-b571-d942f396c488

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk


